// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitemaDeComandas.Context;

#nullable disable

namespace SitemaDeComandas.Migrations
{
    [DbContext(typeof(SistemaComandasContext))]
    [Migration("20241003011911_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComandaProduto", b =>
                {
                    b.Property<int>("ComandasComandaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutosProdutoId")
                        .HasColumnType("int");

                    b.HasKey("ComandasComandaId", "ProdutosProdutoId");

                    b.HasIndex("ProdutosProdutoId");

                    b.ToTable("ComandaProduto");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Comanda", b =>
                {
                    b.Property<int>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaId"));

                    b.Property<int>("CozinhaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SituacaoComandaId")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<bool>("Viagem")
                        .HasColumnType("bit");

                    b.HasKey("ComandaId");

                    b.HasIndex("CozinhaId");

                    b.HasIndex("SituacaoComandaId");

                    b.HasIndex("VendaId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Cozinha", b =>
                {
                    b.Property<int>("CozinhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CozinhaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CozinhaId");

                    b.ToTable("Cozinhas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.FormaPagamento", b =>
                {
                    b.Property<int>("FormaPagamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormaPagamentoId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FormaPagamentoId");

                    b.ToTable("FormasPagamentos");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<int?>("CozinhaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.HasIndex("CozinhaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.ProdutoComanda", b =>
                {
                    b.Property<int>("PratoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PratoComandaId"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("PratoComandaId");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutosComandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.ProdutoVenda", b =>
                {
                    b.Property<int>("ProdutoVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoVendaId"));

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.Property<double>("PrecoUnitario")
                        .HasColumnType("float");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoVendaId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ProdutosVendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoComanda", b =>
                {
                    b.Property<int>("SituacaoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoComandaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituacaoComandaId");

                    b.ToTable("SituacoesComandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoVenda", b =>
                {
                    b.Property<int>("SituacaoVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoVendaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituacaoVendaId");

                    b.ToTable("SituacoesVendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.Property<int?>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("SituacaoVendaId")
                        .HasColumnType("int");

                    b.HasKey("VendaId");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("SituacaoVendaId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("ComandaProduto", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.Comanda", null)
                        .WithMany()
                        .HasForeignKey("ComandasComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutosProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Comanda", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.Cozinha", "Cozinha")
                        .WithMany("Comandas")
                        .HasForeignKey("CozinhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.SituacaoComanda", "SituacaoComanda")
                        .WithMany("Comandas")
                        .HasForeignKey("SituacaoComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.Venda", "Venda")
                        .WithMany("Comandas")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cozinha");

                    b.Navigation("SituacaoComanda");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Produto", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.Cozinha", "Cozinha")
                        .WithMany("Produtos")
                        .HasForeignKey("CozinhaId");

                    b.Navigation("Cozinha");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.ProdutoComanda", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.Comanda", "Comanda")
                        .WithMany()
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.ProdutoVenda", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Venda", b =>
                {
                    b.HasOne("SitemaDeComandas.Models.FormaPagamento", "FormaPagamento")
                        .WithMany("Vendas")
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SitemaDeComandas.Models.Produto", null)
                        .WithMany("Vendas")
                        .HasForeignKey("ProdutoId");

                    b.HasOne("SitemaDeComandas.Models.SituacaoVenda", "SituacaoVenda")
                        .WithMany("Vendas")
                        .HasForeignKey("SituacaoVendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagamento");

                    b.Navigation("SituacaoVenda");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Cozinha", b =>
                {
                    b.Navigation("Comandas");

                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.FormaPagamento", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Produto", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoComanda", b =>
                {
                    b.Navigation("Comandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoVenda", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Venda", b =>
                {
                    b.Navigation("Comandas");
                });
#pragma warning restore 612, 618
        }
    }
}
