// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SitemaDeComandas.Context;

#nullable disable

namespace SitemaDeComandas.Migrations
{
    [DbContext(typeof(SistemaComandasContext))]
    [Migration("20241002232755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SitemaDeComandas.Models.Comanda", b =>
                {
                    b.Property<int>("ComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComandaId"));

                    b.Property<int>("CozinhaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FilaVIP")
                        .HasColumnType("bit");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.Property<bool>("Viagem")
                        .HasColumnType("bit");

                    b.HasKey("ComandaId");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Cozinha", b =>
                {
                    b.Property<int>("CozinhaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CozinhaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CozinhaId");

                    b.ToTable("Cozinhas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.PratoComanda", b =>
                {
                    b.Property<int>("PratoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PratoComandaId"));

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("PratoId")
                        .HasColumnType("int");

                    b.Property<int>("SituacaoId")
                        .HasColumnType("int");

                    b.HasKey("PratoComandaId");

                    b.ToTable("PratosComandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<int?>("CozinhaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Preco")
                        .HasColumnType("float");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.ProdutoVenda", b =>
                {
                    b.Property<int>("ProdutoVendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoVendaId"));

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.Property<double>("PrecoUnitario")
                        .HasColumnType("float");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("ProdutoVendaId");

                    b.ToTable("ProdutosVendas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoComanda", b =>
                {
                    b.Property<int>("SituacaoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoComandaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituacaoComandaId");

                    b.ToTable("SituacoesComandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.SituacaoPratoComanda", b =>
                {
                    b.Property<int>("SituacaoPratoComandaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacaoPratoComandaId"));

                    b.Property<int>("Ativo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SituacaoPratoComandaId");

                    b.ToTable("SituacoesPratosComandas");
                });

            modelBuilder.Entity("SitemaDeComandas.Models.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<bool>("Cancelado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataHoraAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraVenda")
                        .HasColumnType("datetime2");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("int");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.Property<double>("PrecoTotal")
                        .HasColumnType("float");

                    b.HasKey("VendaId");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
